### ISSUE TITLE
Metamorphosis doesn't exclude Gem Kill

### ISSUE THREAD

**Issue by bkimmett** [Xom/Cincomancia#1]
I started a new game and got a wand with Create Wall on #1, Metamorphosis on #3, and Gem Kill on #5. But selecting Metamorphosis marks Gem Kill as not on the same wand.

Latest iOS version of Cinco Paus.

**Comment by Xom** [comment]
I'll look into it when I have time.

**Comment by Xom** [comment]
d71c771d7e4fb2f2a11b3bf572a01a3ba359db58
